services:
 
  mariadb:
    image: mariadb:latest
    container_name: mariadbcleanarch
    hostname: mariadbca
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: grilo007
      MYSQL_DATABASE: ordersystem
      MYSQL_PASSWORD: ordersystem
    ports:
      - 3306:3306
    # volumes:
    #   - .mysql/mysql:/var/lib/mysql
    networks:
      - cleanarchnet

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmqcleanarch
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - cleanarchnet
  cleanarch:
    depends_on:
      - mariadb
      - rabbitmq
    build:
      context: .
    container_name: cleanarch
    hostname: cleanarch
    networks:
      - cleanarchnet
    ports:
      - 8080:8080
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mariadbca
      - DB_PORT=3306
      - DB_USER=ordersystem
      - DB_PASSWORD=ordersystem
      - DB_NAME=ordersystem
      - WEB_SERVER_PORT=:8080
      - AMQP_PORT=5672
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - AMQP_QUEUE=job_queue
      - GRPC_SERVER_PORT=50051
      - GRAPHQL_SERVER_PORT=8081
    deploy:
      restart_policy:
        condition: on-failure

networks:
  cleanarchnet:
    driver: bridge
