services:

  cleanarch:
    depends_on:
      rabbitmq:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    build:
      context: .
    container_name: cleanarch
    hostname: cleanarch
    networks:
      - cleanarchnet
    ports:
      - 8080:8080
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mariadbca
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mysql
      - WEB_SERVER_PORT=:8080
      - AMQP_PORT=5672
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - AMQP_QUEUE=job_queue
      - GRPC_SERVER_PORT=50051
      - GRAPHQL_SERVER_PORT=8081
    deploy:
      restart_policy:
        condition: on-failure
    command: sh -c "migrate -path=sql/migrations -database 'mysql://root:root@tcp(mariadbca:3306)/mysql' up && /app/main"

  mariadb:
    image: mariadb:latest
    container_name: mariadbcleanarch
    hostname: mariadbca
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    # volumes:
    #   - .mysql/mysql:/var/lib/mysql
    networks:
      - cleanarchnet
    healthcheck:
      test: [ "CMD-SHELL", "service mariadb status" ]
      interval: 5s
      timeout: 3s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqcleanarch
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - cleanarchnet
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  cleanarchnet:
    driver: bridge
