// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"database/sql"
	"github.com/antoniofmoliveira/cleanarch/internal/database"
	"github.com/antoniofmoliveira/cleanarch/internal/entity"
	"github.com/antoniofmoliveira/cleanarch/internal/event"
	"github.com/antoniofmoliveira/cleanarch/internal/usecase"
	"github.com/antoniofmoliveira/cleanarch/internal/web"
	"github.com/antoniofmoliveira/cleanarch/pkg/events"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewWebOrderHandler(uc usecase.CreateOrderUseCase) *web.WebOrderHandler {
	webOrderHandler := web.NewWebOrderHandler(uc)
	return webOrderHandler
}

func NewListOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.ListOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderListed := event.NewOrderListed()
	listOrderUseCase := usecase.NewListOrderUseCase(orderRepository, orderListed, eventDispatcher)
	return listOrderUseCase
}

//	func NewWebOrderListHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebListOrderHandler {
//		wire.Build(
//			setOrderRepositoryDependency,
//			setOrderListedEvent,
//			web.NewWebListOrderHandler,
//		)
//		return &web.WebListOrderHandler{}
//	}
func NewWebOrderListHandler(uc usecase.ListOrderUseCase) *web.WebListOrderHandler {
	webListOrderHandler := web.NewWebListOrderHandler(uc)
	return webListOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOtherEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderListed, wire.Bind(new(events.EventInterface), new(*event.OrderListed)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))

var setOrderListedEvent = wire.NewSet(event.NewOrderListed, wire.Bind(new(events.EventInterface), new(*event.OrderListed)))
